version: '3.8'

services:
  web:
    container_name: php
    environment:
      - MYSQL_HOST=$MYSQL_HOST
    build:
      args:
        SECRET_DIR: $SECRET_DIR
      context: $VOLUME_BASE_DIR
      dockerfile: $VOLUME_BASE_DIR/.docker/php/Dockerfile
    volumes:
      - $VOLUME_BASE_DIR:/var/www/html
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    working_dir: /var/www/html
    depends_on:
      - db

  nginx:
    container_name: nginx
    build:
      dockerfile: $VOLUME_BASE_DIR/.docker/nginx/Dockerfile
      context: $VOLUME_BASE_DIR
    ports:
      - "8888:8080"
    volumes:
      - $VOLUME_BASE_DIR:/var/www/html
    restart: on-failure
    depends_on:
      - web

  db:
    image: mariadb:10.6.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    restart: on-failure

  database:
    image: postgres:16.2
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./db/redisdata:/data